// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAwhnA3CJy6MNO6c6vV5yKm9z2zjGWGpU',
    appId: '1:265254202905:web:f9b3539b1213702745c488',
    messagingSenderId: '265254202905',
    projectId: 'balad-news',
    authDomain: 'balad-news.firebaseapp.com',
    storageBucket: 'balad-news.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIe9frV-UaWGk9KxNv9nymG5CY9HRuZ6g',
    appId: '1:265254202905:android:a75c2bde6383d66e45c488',
    messagingSenderId: '265254202905',
    projectId: 'balad-news',
    storageBucket: 'balad-news.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq4msfs1c88dV2awNLZ-evF0_zgpuqwc',
    appId: '1:265254202905:ios:7af8f44f5582644e45c488',
    messagingSenderId: '265254202905',
    projectId: 'balad-news',
    storageBucket: 'balad-news.firebasestorage.app',
    iosBundleId: 'com.example.baladNaw',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq4msfs1c88dV2awNLZ-evF0_zgpuqwc',
    appId: '1:265254202905:ios:7af8f44f5582644e45c488',
    messagingSenderId: '265254202905',
    projectId: 'balad-news',
    storageBucket: 'balad-news.firebasestorage.app',
    iosBundleId: 'com.example.baladNaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAwhnA3CJy6MNO6c6vV5yKm9z2zjGWGpU',
    appId: '1:265254202905:web:e5681a429244f25445c488',
    messagingSenderId: '265254202905',
    projectId: 'balad-news',
    authDomain: 'balad-news.firebaseapp.com',
    storageBucket: 'balad-news.firebasestorage.app',
  );
}
